description: "AGIBOTWORLDCHALLENGE"
target:
  name: agi_bot_challenge
  service: sing
  workspace_name: msra_srobot_azureml

environment:
  registry: SrobotRegistry.azurecr.io
  image: aigbotworld_challenge_training:latest

storage:
  data:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlndata
    mount_dir: /work/data
  pretrained_weights:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlnweights
    mount_dir: /work/weights
  outputs:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlnoutputs
    mount_dir: /work/outputs

code:
  local_dir: $CONFIG_DIR/..

jobs:
  - name: univla_agibot
    identity: managed
    submit_args:
      env:
        _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/msra_srobot/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra_srobot_identity"
    sku: 40G1-A100
    command:
    - sudo cp -r /tmp/amlt-code-download/* /work
    - sudo chown -R aiscuser /opt/conda/envs/ptca
    - echo "test 1"
    # 把用户 aiscuser 加入组 mygroup
    # - sudo usermod -aG sudo aiscuser
    - echo "test 2"
    - bash fix_work_permissions.sh
    - echo "test 3"
    - cd /work && bash set_env.sh 
    - bash 0_start_training.sh
